
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class login extends javax.swing.JFrame {
    /*
        we want to save the customer_id once anybody logged in.
        Because other operations are up to this.
    */
    public static int customer_id;
    
    public login() {
        initComponents();
        
        //puts the window in the middle of the screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nickname_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        icon_username = new javax.swing.JLabel();
        icon_password = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sign_in = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password : ");

        nickname_field.setForeground(new java.awt.Color(204, 204, 204));
        nickname_field.setText("Username");
        nickname_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nickname_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nickname_fieldFocusLost(evt);
            }
        });

        password_field.setText("password");
        password_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_fieldFocusLost(evt);
            }
        });

        icon_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N

        icon_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.png"))); // NOI18N

        login_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Do not you have a user ? ");

        sign_in.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sign_in.setForeground(new java.awt.Color(0, 51, 255));
        sign_in.setText("CLICK HERE TO SIGN IN");
        sign_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_inMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_inMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_inMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(icon_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nickname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sign_in)
                            .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icon_username)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(nickname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(icon_password, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addComponent(login_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sign_in))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nickname_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nickname_fieldFocusGained
        //warning user about that here a username should be given
        if(nickname_field.getText().toLowerCase().equals("username")){
            nickname_field.setText("");
            nickname_field.setForeground(Color.black);
        }
        //once on username field clicked, user will understand he is on username 
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        icon_username.setBorder(border);
    }//GEN-LAST:event_nickname_fieldFocusGained

    private void nickname_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nickname_fieldFocusLost
        //turning the field into becoming its first properties
        if (nickname_field.getText().equals("") || nickname_field.getText().toLowerCase().equals("username")) {
            nickname_field.setText("Username");
            nickname_field.setForeground(new Color(204,204,204));
        }
        
        icon_username.setBorder(null);
    }//GEN-LAST:event_nickname_fieldFocusLost

    private void password_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_fieldFocusGained
        if(String.valueOf(password_field.getPassword()).toLowerCase().equals("password")){
            password_field.setText("");
        }
        //once on username field clicked, user will understand he is on password 
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        icon_password.setBorder(border);
    }//GEN-LAST:event_password_fieldFocusGained

    private void password_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_fieldFocusLost
        String password_var = String.valueOf(password_field.getPassword());
        if(password_var.equals("") || password_var.toLowerCase().equals("password")){
            password_field.setText("password");
        }
        icon_password.setBorder(null);
    }//GEN-LAST:event_password_fieldFocusLost

    private void sign_inMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_inMouseEntered
        sign_in.setForeground(Color.black);
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
        sign_in.setBorder(border);
    }//GEN-LAST:event_sign_inMouseEntered

    private void sign_inMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_inMouseExited
        sign_in.setForeground(new Color(0,51,255));
        sign_in.setBorder(null);
    }//GEN-LAST:event_sign_inMouseExited

    private void sign_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_inMouseClicked
        dispose();
        new signin().setVisible(true);
    }//GEN-LAST:event_sign_inMouseClicked

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        
        if (nickname_field.getText().equals("") || nickname_field.getText().toLowerCase().equals("username") || 
                String.valueOf(password_field.getPassword()).equals("") || String.valueOf(password_field.getPassword()).equals("password")) {
            
            JOptionPane.showMessageDialog(null, "Fields are empty!","EMPTY FIELD",2);
        }
        else{
            String nickname = nickname_field.getText();
            String password = String.valueOf(password_field.getPassword());

            String SQL_expression = "SELECT customer_id FROM customer WHERE customer_nickname=? AND customer_password=?";
            
            try {

                postresql_db_connection db_connection = new postresql_db_connection();
                PreparedStatement st = db_connection.connect().prepareStatement(SQL_expression);
                
                ResultSet rs;
                
                st.setString(1, nickname);
                st.setString(2, password);
                
                rs = st.executeQuery();
                
                if (rs.next()) {
                    customer_id = rs.getInt("customer_id");
                    st.close();
                    JOptionPane.showMessageDialog(null, "Login is successful!");
                    dispose();
                    new book_ui().setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "A User like this does not exist!","NOT EXISTING USER",2);
                    nickname_field.setText("");
                    password_field.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_password;
    private javax.swing.JLabel icon_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField nickname_field;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel sign_in;
    // End of variables declaration//GEN-END:variables
}
