
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.beans.Statement;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class signin extends javax.swing.JFrame {

    /**
     * Creates new form signin
     */
    public signin() {
        initComponents();
        
        //only one button selection is allowed. Therefore we put all buttons into a button group
        ButtonGroup bg = new ButtonGroup();
            bg.add(male_button);
            bg.add(female_button);
        //puts the window in the middle of the screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nickname_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        surname_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        phone_field = new javax.swing.JTextField();
        male_button = new javax.swing.JRadioButton();
        female_button = new javax.swing.JRadioButton();
        street_field = new javax.swing.JTextField();
        house_number_field = new javax.swing.JTextField();
        postcode_field = new javax.swing.JTextField();
        city_field = new javax.swing.JTextField();
        signin_button = new javax.swing.JButton();
        back_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN IN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nickname : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Password :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Surname : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("E-mail :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Phone :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Gender :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Street :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("House nr : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Postcode :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("City :");

        name_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name_fieldKeyTyped(evt);
            }
        });

        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });

        surname_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                surname_fieldKeyTyped(evt);
            }
        });

        phone_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_fieldKeyTyped(evt);
            }
        });

        male_button.setText("Male");

        female_button.setText("Female");
        female_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_buttonActionPerformed(evt);
            }
        });

        house_number_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                house_number_fieldKeyTyped(evt);
            }
        });

        postcode_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                postcode_fieldKeyTyped(evt);
            }
        });

        city_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                city_fieldKeyTyped(evt);
            }
        });

        signin_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signin_button.setText("SIGN IN");
        signin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_buttonActionPerformed(evt);
            }
        });

        back_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        back_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_iconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nickname_field)
                                .addComponent(name_field)
                                .addComponent(password_field, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(surname_field)
                                .addComponent(email_field)
                                .addComponent(phone_field))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(male_button, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(female_button, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(city_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(postcode_field, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(house_number_field, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(street_field, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(signin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(back_icon)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(back_icon)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nickname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(surname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(male_button)
                    .addComponent(female_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(street_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(house_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(postcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(city_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signin_button)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void female_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_buttonActionPerformed

    private void name_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_fieldKeyTyped
        //User can only enter alphabets
        if(!(Character.isAlphabetic(evt.getKeyChar())) || (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar()==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_name_fieldKeyTyped

    private void surname_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surname_fieldKeyTyped
        //User can only enter alphabets
        if(!(Character.isAlphabetic(evt.getKeyChar())) || (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar()==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_surname_fieldKeyTyped

    private void city_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_city_fieldKeyTyped
        //User can only enter alphabets
        if(!(Character.isAlphabetic(evt.getKeyChar())) || (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar()==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_city_fieldKeyTyped

    private void phone_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_fieldKeyTyped
        //only 15 charackters allowed
        if((phone_field.getText() + evt.getKeyChar()).length() >= 16){
            evt.consume();
        }

        //Only numbers as input allowed
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_phone_fieldKeyTyped

    private void house_number_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_house_number_fieldKeyTyped
        //only 5 charackters allowed
        if((house_number_field.getText() + evt.getKeyChar()).length() >= 6){
            evt.consume();
        }

        //Only numbers as input allowed
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_house_number_fieldKeyTyped

    private void postcode_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postcode_fieldKeyTyped
        //only 5 charackters allowed
        if((postcode_field.getText() + evt.getKeyChar()).length() >= 6){
            evt.consume();
        }

        //Only numbers as input allowed
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_postcode_fieldKeyTyped

    private void back_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_iconMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        back_icon.setBorder(border);
    }//GEN-LAST:event_back_iconMouseEntered

    private void back_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_iconMouseExited
        back_icon.setBorder(null);
    }//GEN-LAST:event_back_iconMouseExited

    private void back_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_iconMouseClicked
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_back_iconMouseClicked

    private void signin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_buttonActionPerformed
        String nickname = nickname_field.getText();
        String password = String.valueOf(password_field.getPassword());
        String name = name_field.getText();
        String surname = surname_field.getText();
        String email = email_field.getText();
        String phone = phone_field.getText();
        boolean gender = true;
            if(female_button.isSelected()){
                gender = false;
            }
        String street = street_field.getText();
        String house_number = house_number_field.getText();
        String postcode = postcode_field.getText();
        String city = city_field.getText();
        
        if (inputCheck()) {
                if(!user_existence_check(nickname)){
                    String SQL_expression = "INSERT INTO customer(customer_nickname,customer_password,customer_name,customer_surname,"
                    + "customer_email,customer_phone,customer_gender,customer_street,customer_hause_number,customer_postcode,customer_city) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            
                    // Step 1: Establishing a Connection
                    try {
                        postresql_db_connection db_Connection = new postresql_db_connection();
                        PreparedStatement st = db_Connection.connect().prepareStatement(SQL_expression);

                        st.setString(1, nickname);
                        st.setString(2, password);
                        st.setString(3, name);
                        st.setString(4, surname);
                        st.setString(5, email);
                        st.setString(6, phone);
                        st.setBoolean(7, gender);
                        st.setString(8, street);
                        st.setInt(9, Integer.valueOf(house_number));
                        st.setInt(10, Integer.valueOf(postcode));
                        st.setString(11, city);

                        if(st.executeUpdate() != 0){
                            st.close();
                            JOptionPane.showMessageDialog(null, "New Customer is created!");
                            dispose();
                            new login().setVisible(true);
                        }

                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
        }
    }//GEN-LAST:event_signin_buttonActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signin().setVisible(true);
            }
        });
    }
    boolean inputCheck(){
        String nickname = nickname_field.getText();
        String password = String.valueOf(password_field.getPassword());
        String name = name_field.getText();
        String surname = surname_field.getText();
        String email = email_field.getText();
        String phone = phone_field.getText();
        String street = street_field.getText();
        String house_number = house_number_field.getText();
        String postcode = postcode_field.getText();
        String city = city_field.getText();
        
        if(nickname.trim().equals("") || password.trim().equals("") || name.trim().equals("") || surname.trim().equals("") ||
                email.trim().equals("") || phone.trim().equals("") || street.trim().equals("") || 
                house_number.trim().equals("") || postcode.trim().equals("") || city.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "All fields have to be fullfilled.","ERROR AT INPUT",2);
            return false;
        }
        return true;
    }
    
    boolean user_existence_check(String nickname){
        boolean user_existence = false;
        
        String SQL_expression = "SELECT * FROM customer WHERE customer_nickname=?";
        
        try {
            postresql_db_connection db_Connection = new postresql_db_connection();
            PreparedStatement st = db_Connection.connect().prepareStatement(SQL_expression);
            ResultSet rs;
            
            st.setString(1, nickname);
            rs = st.executeQuery();
            
            if(rs.next()){
                user_existence = true;
                JOptionPane.showMessageDialog(null, "This Nickname has already been taken. Please Change it!","Nickname ERROR",2);
                nickname_field.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return user_existence;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_icon;
    private javax.swing.JTextField city_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JRadioButton female_button;
    private javax.swing.JTextField house_number_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton male_button;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField nickname_field;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField phone_field;
    private javax.swing.JTextField postcode_field;
    private javax.swing.JButton signin_button;
    private javax.swing.JTextField street_field;
    private javax.swing.JTextField surname_field;
    // End of variables declaration//GEN-END:variables
}
